devices/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from profiles.views import profile_info
from .views import *

app_name = 'devices'

urlpatterns = [
    path('', index, name='index'),
    path('devices/', devices_page, name='devices_page'),
]

maek_measuring/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('profiles.urls', namespace='profiles')),
    path('', include('devices.urls', namespace='devices')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from profiles.views import profile_info

app_name = 'profiles'

urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile_info, name='profiles'),
]

templates/layouts/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% if field.field.widget.input_type == 'select' %}
                {% render_field field class="form-select form-control" %}
            {% elif field.field.widget.input_type != 'checkbox' %}
                {% render_field field class="form-control" %}
            {% else %}
                {% render_field field %}
            {% endif %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
{% endfor %}

templates/layouts/nav.html
{% load static %}
{% load i18n %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-body-light out-nav navbar-static-top">
    <div class="container">
        <a class="navbar-brand" href="/"><img src="{% static '/journal/img/logo.png' %}" alt="Logo"></a>
        <button id="navBurger" class="navbar-toggler border-0" aria-label="Button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="{{ home_page }} nav-item">
                    <a class="nav-link" href="{% url 'devices:index' %}">Главная</a>
                </li>
<!--                {% if request.user.profile or request.user.is_superuser %}-->
<!--                    <li class="{{ home_page }} nav-item">-->
<!--                        <a class="nav-link" href="https://power.maek.kz/" target="_blank">Мониторинг Мощности</a>-->
<!--                    </li>-->
<!--                {% endif %}-->
            </ul>
            <ul class="navbar-nav me-4">
                {% if request.user.is_authenticated %}
                    <li>
                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Профиль
                            </a>
                            <ul class="dropdown-menu text-left">
                                <li><a class="dropdown-item" href="{% url 'profiles:profiles' %}">Мой профиль</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'profiles:logout' %}">Выйти</a></li>
                {% elif request.user.is_anonymous %}
                    <li><a href="{% url 'profiles:login' %}">Вход</a></li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>