devices/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from profiles.views import profile_info
from .views import *

app_name = 'devices'

urlpatterns = [
    path('', index, name='index'),
    path('devices/', devices_page, name='devices_page'),
]

maek_measuring/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('profiles.urls', namespace='profiles')),
    path('', include('devices.urls', namespace='devices')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#3f51b5">
    <title>{% block title %}Склад ТОО "МАЭК"{% endblock title %}</title>
    <meta name="description" content="MAЭК">
    <link href="{% static 'journal/img/favicon.ico' %}" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'journal/vendor/bootstrap/css3/bootstrap.min.css' %}?v=1.2" rel="stylesheet">


    <!-- Custom fonts for this template -->
    {#    <!--    <link href="{% static 'journal/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">-->#}

    <!-- Custom styles for this template -->
    <link href="{% static 'journal/css/outwork_style.css' %}?v=1.11" rel="stylesheet" type="text/css">
    {#    <link rel="manifest" href="{% url 'manifest' %}?v=1.4">#}
{#    <link rel="manifest" href="/static/manifest.json?v=1.4">#}

    {% block extra_css %}{% endblock extra_css %}
</head>

<body>
<div id="loader">
    <div class="loader"></div>
</div>
<div id="wrapper">
    {#    <div class="position-absolute w-100 h-100 align-items-center justify-content-center" id="installBlock" style="background: rgba(0, 0, 0, 0.7);z-index: 1000">#}
    {#        <button class="btn btn-primary" id="installButton" style="display: none;">Установить приложение</button>#}
    {#        <button class="btn btn-primary" id="cancelInstallbtn" style="display: none;">Отменить</button>#}
    {#    </div>#}
    {% include 'layouts/nav.html' %}

    <div id="body">
        {% block content %}{% endblock content %}
    </div> <!--body-->

    <!-- Footer -->
    <div id="footer">
        <footer class="footer" style="background: #45485b; color: #c1c1c5">
            <div class="container">
                <div class="row">

                    <div class="col-lg-6 col-md-6 col-xs-12 h-100 text-left">
                        {# <img src="{% static '/journal/img/logo_footer.png' %}"/>#}
                        <h2 class="h6"><b>Контакты</b></h2>
                        <p>Мангистауская область, г. Актау, Промзона 7, здание 65</p>
                        <p>Элекстронный адрес: <a href="mailto:maek@maek.kz" class="text-white">maek@maek.kz</a></p>
                        <!--                        <p>Телефон доверия ТОО «МАЭК» по вопросам закупок: <a href="tel:+77292562100">+7(7292)-->
                        <!--                            562-100</a></p>-->

                        <p class="mt-5">
                            © 2024 ТОО «Мангистауский атомный энергетический комбинат»
                        </p>
                    </div>
                    <div class="col-lg-5 col-md-6 col-xs-12">
                        <!--                        <h6 class="h6">Ответственные лица по закупкам</h6>-->
                        <!--                        <p>Камбаров А.А. - Начальник отдела проведения конкурсных процедур и планирования Департамента-->
                        <!--                            по организации закупок, телефон: <a href="tel:+77292564813">+7(7292) 564813 </a>, -->
                        <!--                            е-mail: <a href="mailto:akambarov@maek.kz">akambarov@maek.kz</a>-->
                        <!--                        </p>-->
                        <!--                        <p>Кадацкая А.А. - Начальник отдела проведения закупа способом из одного источника и ценовых-->
                        <!--                            предложений Департамента по организации закупок, телефон: <a href="tel:+77292564227">+7(7292) 564227</a>, е-mail:-->
                        <!--                            е-mail: <a href="mailto:akadatskaya@maek.kz">akadatskaya@maek.kz</a>-->
                        <!--                        </p>-->
                        <!--{#                        <p>#}-->
                        <!--{#                            Курманбаев Б.Н. - Начальник отдела материально-технического обеспечения Департамента#}-->
                        <!--{#                            материально-технического обеспечения, телефон:<a href="tel:+77292564942">+7 (7292) 564942</a>, е-mail: #}-->
                        <!--{#                            <a href="mailto:bkurmanbaev@maek.kz">#}-->
                        <!--{#                            bkurmanbaev@maek.kz#}-->
                        <!--{#                            </a>#}-->
                        <!--{#                        </p>#}-->
                    </div>
                </div>
            </div>
        </footer>
    </div> <!--footer-->
</div> <!--wrapper-->

<!-- Bootstrap core JavaScript -->

{% block extra_js %}
    <script src="{% static 'journal/vendor/bootstrap/js3/bootstrap.min.js' %}?v=1.1"></script>
    <script src="{% static 'journal/vendor/bootstrap/js3/bootstrap.bundle.min.js' %}?v=1.1"></script>
    <script src="{% static 'journal/vendor/jquery/jquery-2.2.4.min.js' %}"></script>
    <script>
        $("#navBurger").on("click", function () {
            $("#navbarNav").slideToggle("slow", function () {
            });
        });

    </script>
{% endblock extra_js %}
<script>
        $(window).on("load", function () {
            $("#loader").fadeOut("slow"); // После загрузки страницы прячем прелоадер
        });
    </script>
<style>
    /* Стили для прелоадера */
    #loader {
        position: fixed;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.7);
        z-index: 9999;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .loader {
        border: 20px solid #f3f3f3;
        border-radius: 50%;
        border-top: 20px solid #3498db;
        width: 200px;
        height: 200px;
        -webkit-animation: spin 2s linear infinite;
        animation: spin 2s linear infinite;
    }

    @-webkit-keyframes spin {
        0% {
            -webkit-transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
        }
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная{% endblock %}

{% block content %}
<div class="main-blocks">
    <div class="container">
        <div class="mb-5 mt-4">
            <h2 class="h2 text-center">Средства измерения TOO "МАЭК"</h2>
        </div>
        <div class="row">

            <div class="col-xl-4 col-lg-4 col-md-6 col-sm main-block">
                <a href="{% url 'devices:devices_page' %}" class="main_link">
                    <div class="text-center border border-1 rounded p-3 main_block__block">
                        <img src="{% static 'img/home/electric-meter.png' %}"  alt="Схемы" class="w-25 object-fit-contain"/>
                        <p class="h5 mt-2">Приборы</p>
                    </div>
                </a>
            </div>
{#            <div class="col-xl-4 col-lg-4 col-md-6 col-sm main-block">#}
{#                <a href="{% url 'devices:devices_page' %}" class="main_link">#}
{#                    <div class="text-center border border-1 rounded p-3 main_block__block">#}
{#                        <img src="{% static 'img/home/warehouse.png' %}"  alt="Схемы" class="w-25 object-fit-contain"/>#}
{#                        <p class="h5 mt-2">Товары на центральном складе</p>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}

        </div>
    </div>
</div>
{% endblock %}

templates/main_sklad.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Приборы{% endblock %}
{% block content %}
    <div class="contractor_content mb-5">
        <div class="container">
            <h3 class="h3 mt-2 mb-3">Приборы по состоянию на {{ today|date:"d.m.Y" }}</h3>
            <form method="GET" action="{% url 'devices:devices_page' %}" class="w-100">
                <div class="row mb-3 pt-4 pb-4 bg-dark-subtle row-gap-3 ms-0 me-0">
                    <div class="col-3">
                        <label>Поиск по наименованию</label>
                        <input type="text" name="name__icontains" class="form-control"
                               placeholder="Поиск по наименованию" value="{{ request.GET.name__icontains }}">
                    </div>
                    <div class="col-3">
                        <label>Поиск по подразделению</label>
                        <input type="text" name="subdivision__icontains" class="form-control"
                               placeholder="Поиск по подразделению" value="{{ request.GET.subdivision__icontains }}">
                    </div>
                    <div class="col-3">
                        <label>Поиск по заводскому номеру</label>
                        <input type="text" name="factory_number__icontains" class="form-control"
                               placeholder="Поиск по заводскому номеру"
                               value="{{ request.GET.factory_number__icontains }}">
                    </div>
                    <div class="col-3">
                        <label>Поиск по датчикам</label>
                        <input type="text" name="sensor__icontains" class="form-control"
                               placeholder="Поиск по датчикам" value="{{ request.GET.sensor__icontains }}">
                    </div>
                    <div class="col-3">
                        <label>Поиск по количеству</label>
                        <div class="row">
                            <div class="col">
                                <input type="number" name="quantity__gte" class="form-control" placeholder="От"
                                       value="{{ request.GET.quantity__gte }}">
                            </div>
                            <div class="col">
                                <input type="number" name="quantity__lte" class="form-control" placeholder="До"
                                       value="{{ request.GET.quantity__lte }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <label>Поиск по дате выпуска</label>
                        <div class="row">
                            <div class="col">
                                <input type="date" name="date_issued__gte" class="form-control" placeholder="От"
                                       value="{{ request.GET.date_issued__gte }}">
                            </div>
                            <div class="col">
                                <input type="date" name="date_issued__lte" class="form-control" placeholder="До"
                                       value="{{ request.GET.date_issued__lte }}" max="{{ today|date:'Y-m-d' }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <label>Поиск по дате ввода</label>
                        <div class="row">
                            <div class="col">
                                <input type="date" name="date_entry__gte" class="form-control" placeholder="От"
                                       value="{{ request.GET.date_entry__gte }}">
                            </div>
                            <div class="col">
                                <input type="date" name="date_entry__lte" class="form-control" placeholder="До"
                                       value="{{ request.GET.date_entry__lte }}" max="{{ today|date:'Y-m-d' }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <label>Поиск по дате поверки</label>
                        <div class="row">
                            <div class="col">
                                <input type="date" name="date_verification__gte" class="form-control" placeholder="От"
                                       value="{{ request.GET.date_verification__gte }}">
                            </div>
                            <div class="col">
                                <input type="date" name="date_verification__lte" class="form-control" placeholder="До"
                                       value="{{ request.GET.date_verification__lte }}" max="{{ today|date:'Y-m-d' }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <label>Поиск по результату ремонта</label>
                        <input type="text" name="repair_result__icontains" class="form-control"
                               placeholder="Поиск по результату ремонта"
                               value="{{ request.GET.repair_result__icontains }}">
                    </div>
                    <div class="col-3">
                        <label>Поиск по дате следующей поверки</label>
                        <div class="row">
                            <div class="col">
                                <input type="date" name="date_next_verification__gte" class="form-control"
                                       placeholder="От"
                                       value="{{ request.GET.date_next_verification__gte }}">
                            </div>
                            <div class="col">
                                <input type="date" name="date_next_verification__lte" class="form-control"
                                       placeholder="До"
                                       value="{{ request.GET.date_next_verification__lte }}"
                                       max="{{ today|date:'Y-m-d' }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <label>Поиск по состоянию</label>
                        <input type="text" name="state__icontains" class="form-control"
                               placeholder="Поиск по состоянию" value="{{ request.GET.state__icontains }}">
                    </div>
                    <div class="w-100 mt-2">
                        <button type="submit" class="btn btn-primary me-3">Поиск</button>
                        <a href="{% url 'devices:devices_page' %}#nofilter"
                           class="btn btn-primary text-white">Сбросить</a>
                        {#                        <button type="button" id="downloadReportButton" class="btn btn-success text-white ms-3">Скачать#}
                        {#                            отчет#}
                        {#                        </button>#}
                    </div>
                </div>
            </form>


            {% if devices %}
                <div class="h5">
                    <p>Количество записей: <b>{{ devices_count|intcomma }}</b></p>
                    <p>Количество приборов: <b>{{ devices_quantity_count.quantity|intcomma }}</b></p>
                </div>
                <table class="table-bordered border-dark" id="products_table">
                    <thead>
                    <tr>
                        <th>Наименование</th>
                        <th>Подразделение</th>
                        <th>Заводской Номер</th>
                        <th>Датчик</th>
                        <th>Количество</th>
                        <th>Дата Выпуска</th>
                        <th>Дата Ввода</th>
                        <th>Дата Поверки</th>
                        <th>Результат Ремонта</th>
                        <th>Дата Следующей Поверки</th>
                        <th>Состояние</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for device in devices %}
                        <tr class="device_tr">
                            <td class="td_name" style="max-width: 200px">{{ device.name }}</td>
                            <td class="td_subdivision">{{ device.subdivision }}</td>
                            <td class="td_factory_number">{{ device.factory_number }}</td>
                            <td class="td_sensor">{{ device.sensor }}</td>
                            <td class="td_quantity">{{ device.quantity }}</td>
                            <td class="td_date_issued">{{ device.date_issued|date:"d.m.Y" }}</td>
                            <td class="td_date_entry">{{ device.date_entry|date:"d.m.Y" }}</td>
                            <td class="td_date_verification">{{ device.date_verification|date:"d.m.Y" }}</td>
                            <td class="td_repair_result">{{ device.repair_result }}</td>
                            <td class="td_date_next_verification">{{ device.date_next_verification|date:"d.m.Y" }}</td>
                            <td class="td_state">{{ device.state|default_if_none:"" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div>
                    <h3 class="h3">Ничего не найдено</h3>
                </div>
            {% endif %}
            <nav aria-label="Page navigation example">
                <ul class="pagination mt-4">
                    <li class="step-links">
                        {% if devices.has_previous %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page=1{% if search_querydict %}&{{ search_querydict }}{% endif %}"
                                                     aria-label="Previous"><span
                                    aria-hidden="true">&laquo;</span></a></li>
                            <li class="page-item"><a class="page-link"
                                                     href="?page=

                                                             {{ devices.previous_page_number }}{% if search_querydict %}&{{ search_querydict }}{% endif %}">&#8249;</a>
                            </li>
                        {% endif %}
                    </li>

                    {% for page_num in devices.paginator.page_range %}
                        {% if page_num >= devices.number|add:"-2" and page_num <= devices.number|add:"2" %}
                            <li class="page-item {% if page_num == devices.number %}active{% endif %}">
                                <a class="page-link" href="?page=

                                        {{ page_num }}{% if search_querydict %}&{{ search_querydict }}{% endif %}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if devices.has_next %}
                        <li class="page-item"><a class="page-link" href="?page=

                                {{ devices.next_page_number }}{% if search_querydict %}&{{ search_querydict }}{% endif %}">&#8250;</a>
                        </li>
                        <li class="page-item"><a class="page-link"
                                                 href="?page=

                                                         {{ devices.paginator.num_pages }}{% if search_querydict %}&{{ search_querydict }}{% endif %}"><span
                                aria-hidden="true">&raquo;</span>
                        </a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    <script src="{% static 'journal/vendor/jquery/jquery-2.2.4.min.js' %}"></script>

    <script>
        let productsTable = document.getElementById('products_table');
        if (productsTable) {
            let deviceTr = document.querySelectorAll('.device_tr');
            deviceTr.forEach(tr => {
                let repairResult = tr.querySelector('.td_repair_result');
                let dateNextVer = tr.querySelector('.td_date_next_verification');
                let state = tr.querySelector('.td_state');
                if (dateNextVer) {
                    let dateText = dateNextVer.textContent.trim();
                    let [day, month, year] = dateText.split('.').map(num => parseInt(num, 10));
                    let dateValue = new Date(year, month - 1, day); // month is 0-based
                    let todayDate = new Date();
                    todayDate.setHours(0, 0, 0, 0); // Ignore the time part for comparison

                    console.log("dateValue", dateValue);
                    console.log("todayDate", todayDate);
                    console.log("state.textContent", state.textContent);

                    if (repairResult && (repairResult.textContent.trim() === "Годен" || repairResult.textContent.trim() === "") && (dateValue <= todayDate) && (state.textContent.trim() === "В подразделении")) {
                        repairResult.classList.add('bg-warning');
                        tr.classList.add('bg-warning');
                    }
                }
            });
        }

    </script>


{% endblock %}